name: 'GitHub Push'
description: 'Pushing to GitHub repository'
author: 'MJ'
branding:
  icon: upload-cloud
  color: green
inputs:
  you_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}.'
    required: true
  user_email:
    description: 'git config --local user.email "action@github.com"'
    required: false
    default: 'action@github.com'
  user_name:
    description: 'git config --local user.name "GitHub Action"'
    required: false
    default: 'GitHub Action'
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: './'
  folder:
    description: 'Include a folder.'
    required: false
    default: 'dir_upload'
  commit_msg:
    description: 'git commit -m "Add changes" -a'
    required: false
    default: 'Add changes'
  branch:
    description: 'Destination branch to push changes.'
    required: false
    default: 'master'
  force:
    description: 'Determines if force push is used.'
    required: false
  tags:
    description: 'Determines if --tags is used.'
    required: false
runs:
  using: 'node12'
  main: 'start.js'