name: 'GitHub Push'
description: 'Pushing to GitHub repository'
author: 'MJ'
branding:
  icon: upload-cloud
  color: green
inputs:
  you_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}.'
    required: true
  repository:
    description: 'Repository name. Default or empty repository name represents current github repository. If you want to push to other repository, you should make a personal access token and use it as the github_token input.'
    required: false
    default: ''
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: './'
  branch:
    description: 'Destination branch to push changes.'
    required: false
    default: 'master'
  force:
    description: 'Determines if force push is used.'
    required: false
  tags:
    description: 'Determines if --tags is used.'
    required: false
runs:
  using: 'node12'
  main: 'start.js'