name: Validate links

on:
  watch:
    types: [started]

jobs:
  build:
    name: Validate links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        touch testtesttest
        git add ./
        git commit -m "Add changes" -a
    - name: Validate links
      uses: 1005789164/push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: "1005789164"
        repository: "1005789164/save"
        directory: "./.github"
        
